In [1]:
import ultralytics
from ultralytics import YOLO
from ultralytics.yolo.utils.checks import check_yaml
from ultralytics.yolo.utils import ROOT, yaml_load


In [2]:
model = YOLO('D:/ultralytics-main/code/runs/detect/train23/weights/best.pt')


In [3]:
classes = yaml_load(check_yaml('D:/ultralytics-main/figure_find/data.yaml'))['names']

In [4]:
def gen(result):
    results = yield result
    return results

In [5]:
def convert(head, size, box):
    dw = 1./size[0]
    dh = 1./size[1]
    x = (box[0] + box[2])/2.0
    y = (box[1] + box[3])/2.0
    w = box[2] - box[0]
    h = box[3] - box[1]
    x = x*dw
    w = w*dw
    y = y*dh
    h = h*dh
    return (head, x,y,w,h)

In [12]:
import cv2
import numpy as np

colors = np.random.uniform(0, 255, size=(len(classes), 3))
webcam = cv2.VideoCapture(0)
count = 0
if not webcam.isOpened():
    print("Could not open webcam")
    exit()



boxes = []
masks = [] 
while webcam.isOpened():
    status, frame = webcam.read()
    if status:
        
        frame = ~frame
        morph_kernel = np.ones((9, 9), np.uint8)
        morph = cv2.morphologyEx(frame, cv2.MORPH_CLOSE, morph_kernel)
        gray_frame = cv2.cvtColor(morph, cv2.COLOR_BGR2GRAY)
        # # 화면 내 모든 도형 검출
        #gray_frame = gray_frame.transpose((2,0,1))
        contours, _ = cv2.findContours(gray_frame , cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
        cv2.imshow("gray_frame", gray_frame)
        print(gray_frame)

        results= model(gray_frame, stream=True)
        #cv2.imshow("YOLOv8 Inference", contours)
        #results = list(results)
        #annotated_frame = results[0].plot()
        cv2.imshow("test", frame)
        for result in results:
            boxes = result.boxes  # Boxes object for bbox outputs
            masks = result.masks  # Masks object for segmentation masks outputs
            keypoints = result.keypoints  # Keypoints object for pose outputs
            probs = result.probs  # Class probabilities for classification outputs
            print(boxes)
            print(masks)
            print(keypoints)
            print(probs)
        
    #     class_ids = []
    #     confidences = []
    #     bboxes = []
    #     for result in results:
    #         boxes = result.boxes
    #         for box in boxes:
    #             confidence = box.conf

    #             if confidence > 0.5:
    #                 xyxy = []
    #                 for i in box.xyxy.tolist()[0]:
    #                     xyxy.append(int(i))
    #                 bboxes.append(xyxy)
    #                 print(type(xyxy[0]))
    #                 confidences.append(float(confidence.item()))
    #                 class_ids.append(box.cls.tolist()) 
    #     try:            
    #         result_boxes = cv2.dnn.NMSBoxes(bboxes, confidences, 0.5, 0.4, 0.5)

    #         print(result_boxes)
    #         print(type(confidences))
    #         print(bboxes)

    #         # print(result_boxes)
    #         font = cv2.FONT_HERSHEY_PLAIN
    #         depth_list = list()
    #         person_id_list = list()
    #         for i in range(len(bboxes)):
    #             label = str(classes[int(class_ids[i][0])])
    #             if label == 'person':
    #                 if i in result_boxes:
    #                     count += 1 
    #                     bbox = list(map(int, bboxes[i])) 
    #                     x, y, x2, y2 = bbox
    #                     color = colors[i]
    #                     color = (int(color[0]), int(color[1]), int(color[2]))

    #                     cv2.rectangle(frame, (x, y), (x2, y2), color, 2)
    #                     cv2.putText(frame, label, (x, y + 30), font, 3, color, 3)

    #         cv2.imshow("Bgr frame",frame)
    #         print(count)
    #     except:
    #         pass
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
    



webcam.release()
cv2.destroyAllWindows()

[[184 184 184 ... 168 168 168]
 [184 184 184 ... 166 166 166]
 [184 184 184 ... 164 164 164]
 ...
 [ 71  71  71 ... 195 195 196]
 [ 71  71  71 ... 196 196 198]
 [ 72  72  72 ... 197 197 198]]


ValueError: axes don't match array

In [1]:
try:
    for result in results:
        boxes = result.boxes  # Boxes object for bbox outputs
        masks = result.masks  # Masks object for segmentation masks outputs
        keypoints = result.keypoints  # Keypoints object for pose outputs
        probs = result.probs  # Class probabilities for classification outputs
        print("한번")

except:
    print("오류")
    pass

오류


In [7]:
print(results)

<generator object BasePredictor.stream_inference at 0x00000259C2644EE0>


In [7]:
detection = model(frame, stream=True)